user service changes
phanisofttech/user-service pull request #1
Opened 2024-10-02 14:35 UTC by Saikumar2501

user service changes

2024-10-02 15:02 UTC, phanisofttech requested changes

2024-10-02 15:02 UTC, phanisofttech commented on src/main/java/com/pst/user/controller/UserController.java
Remove extra space

2024-10-03 15:52 UTC, Charan9701 requested changes
Change the spelling of adharNumber in database to aadhaarNumber

2024-10-03 15:52 UTC, Charan9701 commented on src/main/java/com/pst/user/controller/UserController.java
> +
Remove extra spaces between imports

2024-10-03 15:52 UTC, Charan9701 commented on src/main/java/com/pst/user/controller/UserController.java
> +	public String deleteUser(@PathVariable("adharNumber") long adharNumber) {
Change the adharNumber spelling to aadhaarNumber

2024-10-08 14:11 UTC, merged